name: Publisher

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment: mainnet
    env:
      NEXT_PUBLIC_ALCHEMY_URL: '${{ secrets.NEXT_PUBLIC_ALCHEMY_URL }}'
      NEXT_PUBLIC_LBSF_CONTRACT_ADDRESS: '${{ secrets.NEXT_PUBLIC_LBSF_CONTRACT_ADDRESS }}'
      NEXT_PUBLIC_USDC_CONTRACT_ADDRESS: '${{ secrets.NEXT_PUBLIC_USDC_CONTRACT_ADDRESS }}'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run Build
        run: yarn build
      - name: Run Export
        run: yarn export
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'
          channelId: live
